import { MigrationInterface, QueryRunner } from "typeorm";

export class TotalMigration1766572149658 implements MigrationInterface {
    name = 'TotalMigration1766572149658'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "email" character varying, "mobile" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT false, "lastActive" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "profilePicId" integer, CONSTRAINT "UQ_d376a9f93bba651f32a2c03a7d3" UNIQUE ("mobile"), CONSTRAINT "REL_92dd04533a2383d8cd834233fd" UNIQUE ("profilePicId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_951b8f1dfc94ac1d0301a14b7e" ON "users" ("uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_d376a9f93bba651f32a2c03a7d" ON "users" ("mobile") `);
        await queryRunner.query(`CREATE TABLE "userDevice" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" integer NOT NULL, "lastLogin" TIMESTAMP, "lastActive" TIMESTAMP, "userAgent" character varying, "lastLogoutTime" TIMESTAMP, "ipAddress" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d9d56d85466ed4356ea156d5cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6b195c4ce27d73366cef2c4b54" ON "userDevice" ("uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f3c9ae281195c7c59cb694980" ON "userDevice" ("userId") `);
        await queryRunner.query(`CREATE TABLE "userAddress" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "name" character varying, "nickName" character varying, "addressLine1" character varying(255), "country" character varying(100), "city" character varying(100), "state" character varying(100), "pinCode" character varying(20), "latitude" numeric(10,5) NOT NULL, "longitude" numeric(10,5) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cc72457f081f2979232261c92a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b251cbfcbf880bcdec80cf36c" ON "userAddress" ("userId") `);
        await queryRunner.query(`CREATE TABLE "carMake" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6c2531bf193ec168f6a92ad408a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carCategory" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_958d11667ae6603d3b9c0d3bc07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cars" ("id" SERIAL NOT NULL, "model" character varying NOT NULL, "makeId" integer NOT NULL, "categoryId" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc218aa84e79b477d55322271b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_642f9276e31cb67bd99041dcf0" ON "cars" ("makeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8f2af5403621c1527f4c76609" ON "cars" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "adminUser" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "userName" character varying NOT NULL, "password" character varying NOT NULL, "role" character varying NOT NULL, "email" character varying, "empCode" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT false, "joiningDate" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f155e50a944f2658dc1ccb477a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9395dcb94215bc65fe851f46f1" ON "adminUser" ("uuid") `);
        await queryRunner.query(`CREATE TABLE "file" ("id" SERIAL NOT NULL, "fileName" character varying NOT NULL, "storageLocation" character varying NOT NULL, "mimeType" character varying NOT NULL, "sizeBytes" bigint NOT NULL, "provider" character varying, "url" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vendorFile" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "fileId" integer NOT NULL, "category" character varying, "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "vendorId" integer, CONSTRAINT "PK_e582dd70084c7c25fd814cc9bf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_557d8f7f3caa323ab1b351b34f" ON "vendorFile" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_673d3529cb9c30b92d01f1be03" ON "vendorFile" ("fileId") `);
        await queryRunner.query(`CREATE TABLE "vendor" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "email" character varying, "mobile" character varying, "isActive" boolean NOT NULL DEFAULT false, "lastActive" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "profilePicId" integer, "vendorCode" character varying, CONSTRAINT "UQ_bca1f65fe9a33663740b8965212" UNIQUE ("mobile"), CONSTRAINT "REL_befefb4e7e3ac02b7e441f96b9" UNIQUE ("profilePicId"), CONSTRAINT "PK_931a23f6231a57604f5a0e32780" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0f79ca681330149b65bf77fca3" ON "vendor" ("uuid") `);
        await queryRunner.query(`CREATE TABLE "bannerCategory" ("id" SERIAL NOT NULL, "displayText" text, "value" character varying, "createdBy" integer NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f4b8b099ce9b09229fa98cc2c87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "banner" ("id" SERIAL NOT NULL, "bgImageId" integer, "title" character varying NOT NULL, "categoryId" integer, "owner" character varying, "vendorId" integer, "homePageView" boolean, "displaySequence" integer, "targetValue" character varying, "startTime" TIMESTAMP WITH TIME ZONE, "endTime" TIMESTAMP WITH TIME ZONE, "createdBy" integer, "updatedBy" integer, "status" character varying, "reviewStatus" character varying, "rejectReason" character varying, "approvedBy" integer, "removedBy" integer, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_dcf950685a5f448c25455a2a5c" UNIQUE ("bgImageId"), CONSTRAINT "PK_6d9e2570b3d85ba37b681cd4256" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d711b49338fb6396c34d80332" ON "banner" ("vendorId") `);
        await queryRunner.query(`CREATE TABLE "services" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "displayName" character varying(100) NOT NULL, "imageId" character varying, "targetValue" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_019d74f7abcdcb5a0113010cb03" UNIQUE ("name"), CONSTRAINT "UQ_a9c61a8e67aeedc9de8d7f7ccf1" UNIQUE ("displayName"), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "adminToken" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" integer NOT NULL, "refreshToken" text NOT NULL, "accessToken" character varying NOT NULL, "refreshTokenExpiry" TIMESTAMP, "refreshTokenStatus" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18485fa0b06d6486aac1472bbe4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_83cbb625983fe26892df4dbec6" ON "adminToken" ("userId") `);
        await queryRunner.query(`CREATE TABLE "adminFile" ("id" SERIAL NOT NULL, "adminId" integer NOT NULL, "fileId" integer NOT NULL, "category" character varying, "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f82888f8385a576cce3864357d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba7d54b06c3b505d1f7fa3c82b" ON "adminFile" ("adminId") `);
        await queryRunner.query(`CREATE INDEX "IDX_562d5397c73e90987a22eaa552" ON "adminFile" ("fileId") `);
        await queryRunner.query(`CREATE TABLE "userToken" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" integer NOT NULL, "deviceId" integer NOT NULL, "refreshToken" text NOT NULL, "accessToken" character varying NOT NULL, "refreshTokenExpiry" TIMESTAMP, "refreshTokenStatus" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57e9636d5325549fd42e0d7a440" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_002c4d6b032daf6b513e1a4cd8" ON "userToken" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed220e4533fb012a59ce1bd7f5" ON "userToken" ("deviceId") `);
        await queryRunner.query(`CREATE TABLE "userOtp" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" integer NOT NULL, "deviceId" integer NOT NULL, "otp" character varying NOT NULL, "otpToken" character varying NOT NULL, "lastRequestedTime" TIMESTAMP NOT NULL, "requestCount" smallint NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e53e492972b6a7f3fd97e34eac8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9005f69a93cc20f32bd0ce114" ON "userOtp" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dbe33a676c9935082befb09f69" ON "userOtp" ("deviceId") `);
        await queryRunner.query(`CREATE TABLE "userFile" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "fileId" integer NOT NULL, "category" character varying, "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e6d5d1e581530e42ccfab60cf7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7edafc32814a96594bb4f0b784" ON "userFile" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e94d897ab3b5ce964b9a2c683" ON "userFile" ("fileId") `);
        await queryRunner.query(`CREATE TABLE "bannerUserTargetConfig" ("id" SERIAL NOT NULL, "displayText" character varying, "value" character varying NOT NULL, "category" character varying NOT NULL, "isFile" boolean NOT NULL DEFAULT false, "fileFieldName" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, "createdBy" integer NOT NULL, CONSTRAINT "PK_7ce0044b45fd5b25c0fe16b9496" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bannerAudienceType" ("id" SERIAL NOT NULL, "bannerId" integer, "bannerConfigId" integer, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_28c34c1d86f8fef142d1d7ba58b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bannerUserTarget" ("id" SERIAL NOT NULL, "bannerId" integer, "userId" integer, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_fb0090cb23dbbcf7f1cca5ecb73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37a8903c29e0e8e9fc8c05dd05" ON "bannerUserTarget" ("bannerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_60ec9b8aa048ea5afa3b2af420" ON "bannerUserTarget" ("userId") `);
        await queryRunner.query(`CREATE TABLE "serviceList" ("id" SERIAL NOT NULL, "displayName" character varying NOT NULL, "value" character varying NOT NULL, "image" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, "imageId" integer, CONSTRAINT "PK_d44cd9a6971e3273bb7422994a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rewardCategory" ("id" SERIAL NOT NULL, "displayText" text, "value" character varying, "createdBy" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_fd9ad6d336a5391a750b8a4ceda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rewardOfferType" ("id" SERIAL NOT NULL, "offerType" character varying NOT NULL, "percentage" integer, "maxAmount" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e77798aa037ab15e4345c6c58b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rewardContribution" ("id" SERIAL NOT NULL, "contributor" character varying NOT NULL, "shinrPercentage" integer, "vendorPercentage" integer, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eb8660cb423e20fd6160fc803cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reward" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text, "summary" text, "sideText" character varying NOT NULL, "categoryId" integer NOT NULL, "displaySequence" integer, "owner" character varying, "vendorId" integer, "dispCouponPage" boolean NOT NULL DEFAULT false, "dispVendorPage" boolean NOT NULL DEFAULT false, "minOrderValue" integer NOT NULL DEFAULT '0', "rewardOfferTypeId" integer NOT NULL, "startDate" TIMESTAMP WITH TIME ZONE, "endDate" TIMESTAMP WITH TIME ZONE, "grabLimit" integer NOT NULL, "maxUsage" integer NOT NULL, "maxUsagePeriod" character varying, "maxUsagePeriodValue" integer, "rewardContributorId" integer NOT NULL, "codeType" character varying, "singleCode" character varying, "status" character varying, "createdBy" integer, "updatedBy" integer, "removedBy" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_a90ea606c229e380fb341838036" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_803149782d76e949e7862c2c02" ON "reward" ("vendorId") `);
        await queryRunner.query(`CREATE TABLE "rewardUserTargetConfig" ("id" SERIAL NOT NULL, "displayText" character varying, "value" character varying NOT NULL, "category" character varying NOT NULL, "isFile" boolean NOT NULL DEFAULT false, "fileFieldName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, "createdBy" integer NOT NULL, CONSTRAINT "PK_c1dab430b6302b0c35e58ab052e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rewardAudienceType" ("id" SERIAL NOT NULL, "rewardId" integer, "rewardConfigId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_20859190c256ff61d26360ecac7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3bbde5fb9e3daaa81e786de20f" ON "rewardAudienceType" ("rewardId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a139b55d402ec719fac3f14925" ON "rewardAudienceType" ("rewardConfigId") `);
        await queryRunner.query(`CREATE TABLE "rewardServiceType" ("id" SERIAL NOT NULL, "rewardId" integer, "serviceId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8f2cda10e23c564ea712c7253cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89a5d89703cbc3eb010b43a92f" ON "rewardServiceType" ("rewardId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3a1a487152d671f8d009c028b" ON "rewardServiceType" ("serviceId") `);
        await queryRunner.query(`CREATE TABLE "rewardUsage" ("id" SERIAL NOT NULL, "rewardId" integer NOT NULL, "userId" integer NOT NULL, "usedCode" character varying, "status" character varying, "appliedAt" TIMESTAMP, "confirmedAt" TIMESTAMP, "usedAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_daefd49f3bee92a2bda934bb8f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b16e20affde1434849199cf2f7" ON "rewardUsage" ("rewardId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a4b0b5b6bbba4c68cb15814e0" ON "rewardUsage" ("userId") `);
        await queryRunner.query(`CREATE TABLE "rewardUserTarget" ("id" SERIAL NOT NULL, "rewardId" integer, "userId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_11d4c6ada35f4a9a74b0affcea2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c13d2fea673b9393cb2861ac35" ON "rewardUserTarget" ("rewardId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a9af71b7596c7b3649ce986b5" ON "rewardUserTarget" ("userId") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_92dd04533a2383d8cd834233fd1" FOREIGN KEY ("profilePicId") REFERENCES "userFile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userDevice" ADD CONSTRAINT "FK_9f3c9ae281195c7c59cb694980a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userAddress" ADD CONSTRAINT "FK_8b251cbfcbf880bcdec80cf36c5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars" ADD CONSTRAINT "FK_642f9276e31cb67bd99041dcf0c" FOREIGN KEY ("makeId") REFERENCES "carMake"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars" ADD CONSTRAINT "FK_b8f2af5403621c1527f4c76609f" FOREIGN KEY ("categoryId") REFERENCES "carCategory"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendorFile" ADD CONSTRAINT "FK_7e747428f6ca1c64157a01765a5" FOREIGN KEY ("vendorId") REFERENCES "vendor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendorFile" ADD CONSTRAINT "FK_673d3529cb9c30b92d01f1be03a" FOREIGN KEY ("fileId") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendor" ADD CONSTRAINT "FK_befefb4e7e3ac02b7e441f96b93" FOREIGN KEY ("profilePicId") REFERENCES "vendorFile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bannerCategory" ADD CONSTRAINT "FK_4af0fffedae782bf4dfcb07c96c" FOREIGN KEY ("createdBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banner" ADD CONSTRAINT "FK_dcf950685a5f448c25455a2a5c3" FOREIGN KEY ("bgImageId") REFERENCES "adminFile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banner" ADD CONSTRAINT "FK_e1f603ae034d531c266b8a57413" FOREIGN KEY ("categoryId") REFERENCES "bannerCategory"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banner" ADD CONSTRAINT "FK_3d711b49338fb6396c34d80332f" FOREIGN KEY ("vendorId") REFERENCES "vendor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banner" ADD CONSTRAINT "FK_3282821e258d5550f29eeaad0c0" FOREIGN KEY ("createdBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banner" ADD CONSTRAINT "FK_d7dbb829c4be94d7dd752a856ff" FOREIGN KEY ("updatedBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banner" ADD CONSTRAINT "FK_89808b7abcdf617ec7f7964837b" FOREIGN KEY ("approvedBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banner" ADD CONSTRAINT "FK_6bc592dbf0cf4aa26cfa09e45bc" FOREIGN KEY ("removedBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adminToken" ADD CONSTRAINT "FK_83cbb625983fe26892df4dbec69" FOREIGN KEY ("userId") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adminFile" ADD CONSTRAINT "FK_ba7d54b06c3b505d1f7fa3c82b0" FOREIGN KEY ("adminId") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adminFile" ADD CONSTRAINT "FK_562d5397c73e90987a22eaa552a" FOREIGN KEY ("fileId") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userToken" ADD CONSTRAINT "FK_002c4d6b032daf6b513e1a4cd8f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userOtp" ADD CONSTRAINT "FK_f9005f69a93cc20f32bd0ce1145" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userOtp" ADD CONSTRAINT "FK_dbe33a676c9935082befb09f695" FOREIGN KEY ("deviceId") REFERENCES "userDevice"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userFile" ADD CONSTRAINT "FK_7edafc32814a96594bb4f0b784d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userFile" ADD CONSTRAINT "FK_5e94d897ab3b5ce964b9a2c6832" FOREIGN KEY ("fileId") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bannerUserTargetConfig" ADD CONSTRAINT "FK_abaa9f1dc0a12db42759c12555c" FOREIGN KEY ("createdBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bannerAudienceType" ADD CONSTRAINT "FK_fc40d54869687b838a9c82d61ec" FOREIGN KEY ("bannerId") REFERENCES "banner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bannerAudienceType" ADD CONSTRAINT "FK_036633ca90752bce52556aca274" FOREIGN KEY ("bannerConfigId") REFERENCES "bannerUserTargetConfig"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bannerUserTarget" ADD CONSTRAINT "FK_37a8903c29e0e8e9fc8c05dd05f" FOREIGN KEY ("bannerId") REFERENCES "banner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bannerUserTarget" ADD CONSTRAINT "FK_60ec9b8aa048ea5afa3b2af420e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "serviceList" ADD CONSTRAINT "FK_6be7f833a43dd4da18c62813edb" FOREIGN KEY ("imageId") REFERENCES "adminFile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardCategory" ADD CONSTRAINT "FK_bc6209df84eb1e75debf1abebe1" FOREIGN KEY ("createdBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_2934baf7d4129fd1392d74582ef" FOREIGN KEY ("categoryId") REFERENCES "rewardCategory"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_803149782d76e949e7862c2c026" FOREIGN KEY ("vendorId") REFERENCES "vendor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_17cafc46ff71710f0e5bc118d84" FOREIGN KEY ("rewardOfferTypeId") REFERENCES "rewardOfferType"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_4ffa5ebcb325c95724048d23a38" FOREIGN KEY ("rewardContributorId") REFERENCES "rewardContribution"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_f8bdcdd0e1b68c80ea9cf165baf" FOREIGN KEY ("createdBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_adf003d227658c4ce702b6956b6" FOREIGN KEY ("updatedBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_2e1af6b8a403c1d416e70ed101e" FOREIGN KEY ("removedBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardUserTargetConfig" ADD CONSTRAINT "FK_b5969f716249333324f18cc2a88" FOREIGN KEY ("createdBy") REFERENCES "adminUser"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardAudienceType" ADD CONSTRAINT "FK_3bbde5fb9e3daaa81e786de20fc" FOREIGN KEY ("rewardId") REFERENCES "reward"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardAudienceType" ADD CONSTRAINT "FK_a139b55d402ec719fac3f149253" FOREIGN KEY ("rewardConfigId") REFERENCES "rewardUserTargetConfig"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardServiceType" ADD CONSTRAINT "FK_89a5d89703cbc3eb010b43a92f7" FOREIGN KEY ("rewardId") REFERENCES "reward"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardServiceType" ADD CONSTRAINT "FK_a3a1a487152d671f8d009c028b9" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardUsage" ADD CONSTRAINT "FK_b16e20affde1434849199cf2f7b" FOREIGN KEY ("rewardId") REFERENCES "reward"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardUsage" ADD CONSTRAINT "FK_9a4b0b5b6bbba4c68cb15814e0c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardUserTarget" ADD CONSTRAINT "FK_c13d2fea673b9393cb2861ac353" FOREIGN KEY ("rewardId") REFERENCES "reward"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewardUserTarget" ADD CONSTRAINT "FK_9a9af71b7596c7b3649ce986b50" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rewardUserTarget" DROP CONSTRAINT "FK_9a9af71b7596c7b3649ce986b50"`);
        await queryRunner.query(`ALTER TABLE "rewardUserTarget" DROP CONSTRAINT "FK_c13d2fea673b9393cb2861ac353"`);
        await queryRunner.query(`ALTER TABLE "rewardUsage" DROP CONSTRAINT "FK_9a4b0b5b6bbba4c68cb15814e0c"`);
        await queryRunner.query(`ALTER TABLE "rewardUsage" DROP CONSTRAINT "FK_b16e20affde1434849199cf2f7b"`);
        await queryRunner.query(`ALTER TABLE "rewardServiceType" DROP CONSTRAINT "FK_a3a1a487152d671f8d009c028b9"`);
        await queryRunner.query(`ALTER TABLE "rewardServiceType" DROP CONSTRAINT "FK_89a5d89703cbc3eb010b43a92f7"`);
        await queryRunner.query(`ALTER TABLE "rewardAudienceType" DROP CONSTRAINT "FK_a139b55d402ec719fac3f149253"`);
        await queryRunner.query(`ALTER TABLE "rewardAudienceType" DROP CONSTRAINT "FK_3bbde5fb9e3daaa81e786de20fc"`);
        await queryRunner.query(`ALTER TABLE "rewardUserTargetConfig" DROP CONSTRAINT "FK_b5969f716249333324f18cc2a88"`);
        await queryRunner.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_2e1af6b8a403c1d416e70ed101e"`);
        await queryRunner.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_adf003d227658c4ce702b6956b6"`);
        await queryRunner.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_f8bdcdd0e1b68c80ea9cf165baf"`);
        await queryRunner.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_4ffa5ebcb325c95724048d23a38"`);
        await queryRunner.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_17cafc46ff71710f0e5bc118d84"`);
        await queryRunner.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_803149782d76e949e7862c2c026"`);
        await queryRunner.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_2934baf7d4129fd1392d74582ef"`);
        await queryRunner.query(`ALTER TABLE "rewardCategory" DROP CONSTRAINT "FK_bc6209df84eb1e75debf1abebe1"`);
        await queryRunner.query(`ALTER TABLE "serviceList" DROP CONSTRAINT "FK_6be7f833a43dd4da18c62813edb"`);
        await queryRunner.query(`ALTER TABLE "bannerUserTarget" DROP CONSTRAINT "FK_60ec9b8aa048ea5afa3b2af420e"`);
        await queryRunner.query(`ALTER TABLE "bannerUserTarget" DROP CONSTRAINT "FK_37a8903c29e0e8e9fc8c05dd05f"`);
        await queryRunner.query(`ALTER TABLE "bannerAudienceType" DROP CONSTRAINT "FK_036633ca90752bce52556aca274"`);
        await queryRunner.query(`ALTER TABLE "bannerAudienceType" DROP CONSTRAINT "FK_fc40d54869687b838a9c82d61ec"`);
        await queryRunner.query(`ALTER TABLE "bannerUserTargetConfig" DROP CONSTRAINT "FK_abaa9f1dc0a12db42759c12555c"`);
        await queryRunner.query(`ALTER TABLE "userFile" DROP CONSTRAINT "FK_5e94d897ab3b5ce964b9a2c6832"`);
        await queryRunner.query(`ALTER TABLE "userFile" DROP CONSTRAINT "FK_7edafc32814a96594bb4f0b784d"`);
        await queryRunner.query(`ALTER TABLE "userOtp" DROP CONSTRAINT "FK_dbe33a676c9935082befb09f695"`);
        await queryRunner.query(`ALTER TABLE "userOtp" DROP CONSTRAINT "FK_f9005f69a93cc20f32bd0ce1145"`);
        await queryRunner.query(`ALTER TABLE "userToken" DROP CONSTRAINT "FK_002c4d6b032daf6b513e1a4cd8f"`);
        await queryRunner.query(`ALTER TABLE "adminFile" DROP CONSTRAINT "FK_562d5397c73e90987a22eaa552a"`);
        await queryRunner.query(`ALTER TABLE "adminFile" DROP CONSTRAINT "FK_ba7d54b06c3b505d1f7fa3c82b0"`);
        await queryRunner.query(`ALTER TABLE "adminToken" DROP CONSTRAINT "FK_83cbb625983fe26892df4dbec69"`);
        await queryRunner.query(`ALTER TABLE "banner" DROP CONSTRAINT "FK_6bc592dbf0cf4aa26cfa09e45bc"`);
        await queryRunner.query(`ALTER TABLE "banner" DROP CONSTRAINT "FK_89808b7abcdf617ec7f7964837b"`);
        await queryRunner.query(`ALTER TABLE "banner" DROP CONSTRAINT "FK_d7dbb829c4be94d7dd752a856ff"`);
        await queryRunner.query(`ALTER TABLE "banner" DROP CONSTRAINT "FK_3282821e258d5550f29eeaad0c0"`);
        await queryRunner.query(`ALTER TABLE "banner" DROP CONSTRAINT "FK_3d711b49338fb6396c34d80332f"`);
        await queryRunner.query(`ALTER TABLE "banner" DROP CONSTRAINT "FK_e1f603ae034d531c266b8a57413"`);
        await queryRunner.query(`ALTER TABLE "banner" DROP CONSTRAINT "FK_dcf950685a5f448c25455a2a5c3"`);
        await queryRunner.query(`ALTER TABLE "bannerCategory" DROP CONSTRAINT "FK_4af0fffedae782bf4dfcb07c96c"`);
        await queryRunner.query(`ALTER TABLE "vendor" DROP CONSTRAINT "FK_befefb4e7e3ac02b7e441f96b93"`);
        await queryRunner.query(`ALTER TABLE "vendorFile" DROP CONSTRAINT "FK_673d3529cb9c30b92d01f1be03a"`);
        await queryRunner.query(`ALTER TABLE "vendorFile" DROP CONSTRAINT "FK_7e747428f6ca1c64157a01765a5"`);
        await queryRunner.query(`ALTER TABLE "cars" DROP CONSTRAINT "FK_b8f2af5403621c1527f4c76609f"`);
        await queryRunner.query(`ALTER TABLE "cars" DROP CONSTRAINT "FK_642f9276e31cb67bd99041dcf0c"`);
        await queryRunner.query(`ALTER TABLE "userAddress" DROP CONSTRAINT "FK_8b251cbfcbf880bcdec80cf36c5"`);
        await queryRunner.query(`ALTER TABLE "userDevice" DROP CONSTRAINT "FK_9f3c9ae281195c7c59cb694980a"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_92dd04533a2383d8cd834233fd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a9af71b7596c7b3649ce986b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c13d2fea673b9393cb2861ac35"`);
        await queryRunner.query(`DROP TABLE "rewardUserTarget"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a4b0b5b6bbba4c68cb15814e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b16e20affde1434849199cf2f7"`);
        await queryRunner.query(`DROP TABLE "rewardUsage"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3a1a487152d671f8d009c028b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89a5d89703cbc3eb010b43a92f"`);
        await queryRunner.query(`DROP TABLE "rewardServiceType"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a139b55d402ec719fac3f14925"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bbde5fb9e3daaa81e786de20f"`);
        await queryRunner.query(`DROP TABLE "rewardAudienceType"`);
        await queryRunner.query(`DROP TABLE "rewardUserTargetConfig"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_803149782d76e949e7862c2c02"`);
        await queryRunner.query(`DROP TABLE "reward"`);
        await queryRunner.query(`DROP TABLE "rewardContribution"`);
        await queryRunner.query(`DROP TABLE "rewardOfferType"`);
        await queryRunner.query(`DROP TABLE "rewardCategory"`);
        await queryRunner.query(`DROP TABLE "serviceList"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60ec9b8aa048ea5afa3b2af420"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37a8903c29e0e8e9fc8c05dd05"`);
        await queryRunner.query(`DROP TABLE "bannerUserTarget"`);
        await queryRunner.query(`DROP TABLE "bannerAudienceType"`);
        await queryRunner.query(`DROP TABLE "bannerUserTargetConfig"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e94d897ab3b5ce964b9a2c683"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7edafc32814a96594bb4f0b784"`);
        await queryRunner.query(`DROP TABLE "userFile"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbe33a676c9935082befb09f69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9005f69a93cc20f32bd0ce114"`);
        await queryRunner.query(`DROP TABLE "userOtp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed220e4533fb012a59ce1bd7f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_002c4d6b032daf6b513e1a4cd8"`);
        await queryRunner.query(`DROP TABLE "userToken"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_562d5397c73e90987a22eaa552"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba7d54b06c3b505d1f7fa3c82b"`);
        await queryRunner.query(`DROP TABLE "adminFile"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83cbb625983fe26892df4dbec6"`);
        await queryRunner.query(`DROP TABLE "adminToken"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d711b49338fb6396c34d80332"`);
        await queryRunner.query(`DROP TABLE "banner"`);
        await queryRunner.query(`DROP TABLE "bannerCategory"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f79ca681330149b65bf77fca3"`);
        await queryRunner.query(`DROP TABLE "vendor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_673d3529cb9c30b92d01f1be03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_557d8f7f3caa323ab1b351b34f"`);
        await queryRunner.query(`DROP TABLE "vendorFile"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9395dcb94215bc65fe851f46f1"`);
        await queryRunner.query(`DROP TABLE "adminUser"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8f2af5403621c1527f4c76609"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_642f9276e31cb67bd99041dcf0"`);
        await queryRunner.query(`DROP TABLE "cars"`);
        await queryRunner.query(`DROP TABLE "carCategory"`);
        await queryRunner.query(`DROP TABLE "carMake"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b251cbfcbf880bcdec80cf36c"`);
        await queryRunner.query(`DROP TABLE "userAddress"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f3c9ae281195c7c59cb694980"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b195c4ce27d73366cef2c4b54"`);
        await queryRunner.query(`DROP TABLE "userDevice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d376a9f93bba651f32a2c03a7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_951b8f1dfc94ac1d0301a14b7e"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
